# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 376dbf46388d29a526b162ae874f031c6d68aa011c1f27623f56b8914a7649ca6e876188a8ebbf2215aad3471dcb3f7135b8e053b76ac7717f59c6d8d37add89

test:
  secret_key_base: 002b77562ff9c7dc4a2f603f5fd939f1ecdda800cc2dd6f0d7f3312dc0591fb0f25c17d6dd80d5e197093ce620677f0ae6ac7c20bf802b81930a9b9628732f1f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
